USE Everett;

-- 50 modelagens e estilos aplicaveis a vestuario.
INSERT INTO modelos (nomeModelo) VALUES
('Regular Fit'),
('Comfort Fit'),
('Relaxed Fit'),
('Athletic Fit'),
('Muscle Fit'),
('Boyfriend'),
('Mom Fit'),
('Wide Leg'),
('Bootcut'),
('Flare'),
('Cropped'),
('Cintura Alta'),
('Cintura Media'),
('Cintura Baixa'),
('Evasê'),
('Godê'),
('Envelope'),
('Tubinho'),
('Império'),
('Sereia'),
('Princesa'),
('Chemise'),
('Longline'),
('Boxy'),
('Baby Look'),
('Raglan'),
('Ciganinha'),
('Tomara que Caia'),
('Frente Unica'),
('Ombro a Ombro'),
('Gola Alta'),
('Gola Polo'),
('Gola V'),
('Gola Careca'),
('Manga Bufante'),
('Manga Morcego'),
('Manga Japonesa'),
('Cargo'),
('Jogger'),
('Paperbag'),
('Pantacourt'),
('Alfaiataria Slim'),
('Alfaiataria Reta'),
('Anorak'),
('Biker'),
('Bomber'),
('Trucker'),
('Puffer'),
('Parka'),
('Trench Coat');
