USE Everett;

-- 50 subcategorias de pecas e acessorios de vestuario.
INSERT INTO subcategorias (nomeSubcategoria) VALUES
('Regatas'),
('Polos'),
('Camisas de Linho'),
('Blusas de Manga Longa'),
('Croppeds'),
('Bodies'),
('Tunicas'),
('Cardigans'),
('Sueteres'),
('Coletes'),
('Blazers'),
('Parkas'),
('Sobretudos'),
('Corta-ventos'),
('Calcas de Alfaiataria'),
('Calcas Cargo'),
('Calcas Jogger'),
('Calcas Pantacourt'),
('Calcas Flare'),
('Calcas Legging'),
('Shorts Jeans'),
('Shorts de Sarja'),
('Bermudas de Banho'),
('Saias Midi'),
('Saias Longas'),
('Vestidos Curtos'),
('Vestidos Longos'),
('Vestidos de Festa'),
('Macacoes'),
('Macaquinhos'),
('Conjuntos'),
('Biquinis'),
('Maios'),
('Saidas de Praia'),
('Sungas'),
('Cuecas'),
('Calcinhas'),
('Sutias'),
('Camisolas'),
('Robes'),
('Meias Cano Curto'),
('Meias Cano Longo'),
('Tenis'),
('Sandalias'),
('Botas'),
('Sapatilhas'),
('Mocassins'),
('Bolsas Transversais'),
('Mochilas'),
('Cintos de Couro');
