USE Everett;

-- 50 produtos. Em uma instalacao nova, os IDs abaixo correspondem aos registros
-- inseridos pelas migrations 021 a 025.
SET @data_migration = '2026-09-08 12:00:00';

INSERT INTO produtos (
    sku, nome, nomeCombinacao, descricao, genero, preco,
    idCategoria, idSubcategoria, idCor, idTamanho, idModelo,
    imagem1, imagem2, imagem3, imagem4, estoque, ativo, createdAt, updatedAt
) VALUES
('POL-ROY-M-001', 'Polo Piquet Royal', 'Polo Piquet - Azul Royal - M - Regular Fit', 'Polo masculina em piquet de algodao para uso casual.', 'Masculino', 89.90, 8, 13, 28, 3, 11, 'polo-piquet-royal-frente.jpg', 'polo-piquet-royal-costas.jpg', NULL, NULL, 80, 1, @data_migration, @data_migration),
('REG-OFF-P-002', 'Regata Canelada Off White', 'Regata Canelada - Off White - P - Comfort Fit', 'Regata feminina canelada macia e versatil.', 'Feminino', 49.90, 9, 12, 16, 2, 12, 'regata-canelada-off-white.jpg', NULL, NULL, NULL, 95, 1, @data_migration, @data_migration),
('CAM-ARE-G-003', 'Camisa de Linho Areia', 'Camisa de Linho - Areia - G - Relaxed Fit', 'Camisa masculina leve em mistura de linho.', 'Masculino', 159.90, 8, 14, 18, 4, 13, 'camisa-linho-areia-frente.jpg', 'camisa-linho-areia-costas.jpg', NULL, NULL, 42, 1, @data_migration, @data_migration),
('REG-GRA-G-004', 'Regata Esportiva Grafite', 'Regata Esportiva - Grafite - G - Athletic Fit', 'Regata respiravel indicada para treinos intensos.', 'Masculino', 69.90, 15, 12, 26, 4, 14, 'regata-esportiva-grafite.jpg', NULL, NULL, NULL, 110, 1, @data_migration, @data_migration),
('CAM-PRE-G-005', 'Camiseta Muscle Preta', 'Camiseta Muscle - Preto Estonado - G', 'Camiseta ajustada com elastano e toque macio.', 'Masculino', 74.90, 23, 1, 63, 4, 15, 'camiseta-muscle-preta.jpg', NULL, NULL, NULL, 65, 1, @data_migration, @data_migration),
('JEA-AZU-40-006', 'Jeans Boyfriend Azul', 'Jeans Boyfriend - Azul Jeans - 40', 'Calca jeans feminina de caimento solto e confortavel.', 'Feminino', 169.90, 41, 2, 31, 9, 16, 'jeans-boyfriend-azul-frente.jpg', 'jeans-boyfriend-azul-costas.jpg', NULL, NULL, 55, 1, @data_migration, @data_migration),
('JEA-CLA-38-007', 'Jeans Mom Claro', 'Jeans Mom Fit - Azul Celeste - 38', 'Calca jeans feminina de cintura alta e corte vintage.', 'Feminino', 179.90, 41, 2, 30, 8, 17, 'jeans-mom-claro-frente.jpg', 'jeans-mom-claro-costas.jpg', NULL, NULL, 48, 1, @data_migration, @data_migration),
('CAL-TAU-M-008', 'Calca Wide Leg Taupe', 'Calca Wide Leg - Taupe - M', 'Calca feminina ampla com tecido de alfaiataria.', 'Feminino', 189.90, 13, 26, 22, 3, 18, 'calca-wide-leg-taupe.jpg', NULL, NULL, NULL, 36, 1, @data_migration, @data_migration),
('JEA-IND-42-009', 'Jeans Bootcut Indigo', 'Jeans Bootcut - Azul Jeans - 42', 'Jeans masculino bootcut com lavagem escura.', 'Masculino', 179.90, 41, 2, 31, 10, 19, 'jeans-bootcut-indigo.jpg', NULL, NULL, NULL, 47, 1, @data_migration, @data_migration),
('CAL-MAR-40-010', 'Calca Flare Marsala', 'Calca Flare - Marsala - 40', 'Calca feminina flare de cintura alta.', 'Feminino', 149.90, 9, 30, 53, 9, 20, 'calca-flare-marsala.jpg', NULL, NULL, NULL, 52, 1, @data_migration, @data_migration),
('CRO-LIL-P-011', 'Cropped Lilas', 'Cropped - Lilas - P', 'Cropped feminino em malha encorpada.', 'Feminino', 59.90, 9, 16, 39, 2, 21, 'cropped-lilas.jpg', NULL, NULL, NULL, 88, 1, @data_migration, @data_migration),
('CAL-CAQ-38-012', 'Calca Cintura Alta Caqui', 'Calca de Alfaiataria - Caqui - 38 - Cintura Alta', 'Calca feminina estruturada para looks de trabalho.', 'Feminino', 199.90, 13, 26, 19, 8, 22, 'calca-cintura-alta-caqui.jpg', NULL, NULL, NULL, 34, 1, @data_migration, @data_migration),
('BER-OLI-42-013', 'Bermuda Sarja Oliva', 'Bermuda de Sarja - Verde Oliva - 42 - Cintura Media', 'Bermuda masculina de sarja com cinco bolsos.', 'Masculino', 109.90, 8, 33, 34, 10, 23, 'bermuda-sarja-oliva.jpg', NULL, NULL, NULL, 70, 1, @data_migration, @data_migration),
('JEA-PRE-36-014', 'Jeans Cintura Baixa Preto', 'Jeans - Preto Estonado - 36 - Cintura Baixa', 'Calca jeans feminina com lavagem estonada.', 'Feminino', 159.90, 33, 2, 63, 7, 24, 'jeans-cintura-baixa-preto.jpg', NULL, NULL, NULL, 41, 1, @data_migration, @data_migration),
('SAI-CAR-M-015', 'Saia Midi Evase Caramelo', 'Saia Midi - Caramelo - M - Evase', 'Saia midi feminina com movimento e cintura marcada.', 'Feminino', 139.90, 9, 35, 20, 3, 25, 'saia-midi-evase-caramelo.jpg', NULL, NULL, NULL, 38, 1, @data_migration, @data_migration),
('SAI-GEL-P-016', 'Saia Gode Branco Gelo', 'Saia Midi - Branco Gelo - P - Gode', 'Saia feminina rodada em tecido leve.', 'Feminino', 129.90, 55, 35, 64, 2, 26, 'saia-gode-branco-gelo.jpg', NULL, NULL, NULL, 29, 1, @data_migration, @data_migration),
('VES-TER-M-017', 'Vestido Envelope Terracota', 'Vestido Curto - Terracota - M - Envelope', 'Vestido feminino transpassado com faixa ajustavel.', 'Feminino', 169.90, 9, 37, 49, 3, 27, 'vestido-envelope-terracota.jpg', NULL, NULL, NULL, 44, 1, @data_migration, @data_migration),
('VES-PRE-P-018', 'Vestido Tubinho Preto', 'Vestido de Festa - Preto - P - Tubinho', 'Vestido classico ajustado para eventos noturnos.', 'Feminino', 239.90, 14, 39, 2, 2, 28, 'vestido-tubinho-preto.jpg', NULL, NULL, NULL, 24, 1, @data_migration, @data_migration),
('VES-BLU-G-019', 'Vestido Imperio Blush', 'Vestido Longo - Rosa Blush - G - Imperio', 'Vestido longo de cintura elevada e saia fluida.', 'Feminino', 259.90, 24, 38, 43, 4, 29, 'vestido-imperio-blush.jpg', NULL, NULL, NULL, 26, 1, @data_migration, @data_migration),
('VES-BOR-M-020', 'Vestido Sereia Borgonha', 'Vestido de Festa - Borgonha - M - Sereia', 'Vestido longo de festa com modelagem sereia.', 'Feminino', 399.90, 14, 39, 54, 3, 30, 'vestido-sereia-borgonha.jpg', 'vestido-sereia-borgonha-costas.jpg', NULL, NULL, 18, 1, @data_migration, @data_migration),
('VES-NOI-M-021', 'Vestido Noiva Princesa', 'Vestido Longo - Off White - M - Princesa', 'Vestido de noiva com saia volumosa e corpete estruturado.', 'Feminino', 1299.90, 53, 38, 16, 3, 31, 'vestido-noiva-princesa.jpg', 'vestido-noiva-princesa-costas.jpg', NULL, NULL, 8, 1, @data_migration, @data_migration),
('VES-CEL-G-022', 'Vestido Chemise Celeste', 'Vestido Curto - Azul Celeste - G - Chemise', 'Vestido chemise leve com faixa na cintura.', 'Feminino', 189.90, 9, 37, 30, 4, 32, 'vestido-chemise-celeste.jpg', NULL, NULL, NULL, 33, 1, @data_migration, @data_migration),
('COB-CIN-G-023', 'Colete Longline Chumbo', 'Colete - Cinza Chumbo - G - Longline', 'Colete feminino alongado de alfaiataria.', 'Feminino', 179.90, 13, 21, 25, 4, 33, 'colete-longline-chumbo.jpg', NULL, NULL, NULL, 31, 1, @data_migration, @data_migration),
('CAM-OFF-M-024', 'Camiseta Boxy Off White', 'Camiseta - Off White - M - Boxy', 'Camiseta unissex ampla em algodao certificado.', 'Unissex', 79.90, 34, 1, 16, 3, 34, 'camiseta-boxy-off-white.jpg', NULL, NULL, NULL, 120, 1, @data_migration, @data_migration),
('CAM-PIN-P-025', 'Camiseta Baby Look Pink', 'Camiseta - Rosa Pink - P - Baby Look', 'Camiseta feminina ajustada em malha macia.', 'Feminino', 64.90, 35, 1, 45, 2, 35, 'camiseta-baby-look-pink.jpg', NULL, NULL, NULL, 90, 1, @data_migration, @data_migration),
('MOL-MIL-G-026', 'Moletom Raglan Militar', 'Moletom - Verde Militar - G - Raglan', 'Moletom unissex com mangas raglan e interior flanelado.', 'Unissex', 149.90, 32, 8, 35, 4, 36, 'moletom-raglan-militar.jpg', NULL, NULL, NULL, 58, 1, @data_migration, @data_migration),
('BLU-LAV-M-027', 'Blusa Ciganinha Lavanda', 'Blusa Manga Longa - Lavanda - M - Ciganinha', 'Blusa feminina ombro a ombro com caimento leve.', 'Feminino', 99.90, 9, 15, 40, 3, 37, 'blusa-ciganinha-lavanda.jpg', NULL, NULL, NULL, 46, 1, @data_migration, @data_migration),
('VES-CER-P-028', 'Vestido Tomara que Caia Cereja', 'Vestido Curto - Cereja - P - Tomara que Caia', 'Vestido de festa curto com corpete estruturado.', 'Feminino', 229.90, 14, 37, 55, 2, 38, 'vestido-tomara-que-caia-cereja.jpg', NULL, NULL, NULL, 22, 1, @data_migration, @data_migration),
('BLU-NUD-G-030', 'Blusa Ombro a Ombro Nude', 'Blusa Manga Longa - Nude - G - Ombro a Ombro', 'Blusa feminina elegante em malha fria.', 'Feminino', 109.90, 55, 15, 65, 4, 40, 'blusa-ombro-a-ombro-nude.jpg', NULL, NULL, NULL, 43, 1, @data_migration, @data_migration),
('SUE-CAM-G-031', 'Sueter Gola Alta Camel', 'Sueter - Camel - G - Gola Alta', 'Sueter masculino em tricot macio para dias frios.', 'Masculino', 189.90, 37, 20, 21, 4, 41, 'sueter-gola-alta-camel.jpg', NULL, NULL, NULL, 37, 1, @data_migration, @data_migration),
('POL-MEN-M-032', 'Polo Menta', 'Polo - Verde Menta - M - Gola Polo', 'Polo feminina leve com acabamento canelado.', 'Feminino', 99.90, 9, 13, 33, 3, 42, 'polo-menta.jpg', NULL, NULL, NULL, 62, 1, @data_migration, @data_migration),
('CAM-CRE-M-033', 'Camiseta Gola V Creme', 'Camiseta - Creme - M - Gola V', 'Camiseta basica unissex de algodao penteado.', 'Unissex', 59.90, 35, 1, 17, 3, 43, 'camiseta-gola-v-creme.jpg', NULL, NULL, NULL, 135, 1, @data_migration, @data_migration),
('CAM-OCR-G-034', 'Camiseta Gola Careca Ocre', 'Camiseta - Amarelo Ocre - G - Gola Careca', 'Camiseta masculina casual de malha sustentavel.', 'Masculino', 69.90, 34, 1, 58, 4, 44, 'camiseta-gola-careca-ocre.jpg', NULL, NULL, NULL, 105, 1, @data_migration, @data_migration),
('BLU-ROS-M-035', 'Blusa Manga Bufante Rosa Antigo', 'Blusa Manga Longa - Rosa Antigo - M - Manga Bufante', 'Blusa feminina romantica com mangas volumosas.', 'Feminino', 129.90, 9, 15, 44, 3, 45, 'blusa-manga-bufante-rosa-antigo.jpg', NULL, NULL, NULL, 35, 1, @data_migration, @data_migration),
('BLU-AME-G-036', 'Blusa Manga Morcego Ameixa', 'Blusa Manga Longa - Roxo Ameixa - G - Manga Morcego', 'Blusa feminina ampla de caimento confortavel.', 'Feminino', 119.90, 24, 15, 41, 4, 46, 'blusa-manga-morcego-ameixa.jpg', NULL, NULL, NULL, 32, 1, @data_migration, @data_migration),
('TUN-SAL-M-037', 'Tunica Manga Japonesa Salmao', 'Tunica - Salmao - M - Manga Japonesa', 'Tunica feminina leve para producoes casuais.', 'Feminino', 139.90, 9, 18, 48, 3, 47, 'tunica-manga-japonesa-salmao.jpg', NULL, NULL, NULL, 28, 1, @data_migration, @data_migration),
('CAL-CAQ-44-038', 'Calca Cargo Caqui', 'Calca Cargo - Caqui - 44', 'Calca masculina resistente com bolsos utilitarios.', 'Masculino', 169.90, 32, 27, 19, 11, 48, 'calca-cargo-caqui.jpg', NULL, NULL, NULL, 51, 1, @data_migration, @data_migration),
('CAL-GRA-G-039', 'Calca Jogger Grafite', 'Calca Jogger - Grafite - G', 'Calca unissex confortavel com punhos e cordao.', 'Unissex', 129.90, 32, 28, 26, 4, 49, 'calca-jogger-grafite.jpg', NULL, NULL, NULL, 77, 1, @data_migration, @data_migration),
('CAL-FEN-M-040', 'Calca Paperbag Fendi', 'Calca de Alfaiataria - Fendi - M - Paperbag', 'Calca feminina com cintura franzida e faixa.', 'Feminino', 179.90, 13, 26, 23, 3, 50, 'calca-paperbag-fendi.jpg', NULL, NULL, NULL, 30, 1, @data_migration, @data_migration),
('CAL-CEL-M-041', 'Pantacourt Celeste', 'Calca Pantacourt - Azul Celeste - M', 'Calca feminina pantacourt em tecido fluido.', 'Feminino', 159.90, 9, 29, 30, 3, 51, 'calca-pantacourt-celeste.jpg', NULL, NULL, NULL, 33, 1, @data_migration, @data_migration),
('CAL-CHU-42-042', 'Calca Social Slim Chumbo', 'Calca de Alfaiataria - Cinza Chumbo - 42 - Slim', 'Calca social masculina de corte ajustado.', 'Masculino', 219.90, 54, 26, 25, 10, 52, 'calca-social-slim-chumbo.jpg', NULL, NULL, NULL, 40, 1, @data_migration, @data_migration),
('CAL-CAF-40-043', 'Calca Social Reta Cafe', 'Calca de Alfaiataria - Cafe - 40 - Reta', 'Calca social feminina de corte reto e acabamento premium.', 'Feminino', 229.90, 55, 26, 62, 9, 53, 'calca-social-reta-cafe.jpg', NULL, NULL, NULL, 27, 1, @data_migration, @data_migration),
('JAQ-PET-G-044', 'Anorak Azul Petroleo', 'Corta-vento - Azul Petroleo - G - Anorak', 'Jaqueta unissex impermeavel com capuz ajustavel.', 'Unissex', 249.90, 39, 25, 27, 4, 54, 'anorak-azul-petroleo.jpg', NULL, NULL, NULL, 45, 1, @data_migration, @data_migration),
('JAQ-PRE-M-045', 'Jaqueta Biker Preta', 'Jaqueta - Preto - M - Biker', 'Jaqueta feminina estilo biker em material sintetico.', 'Feminino', 299.90, 43, 4, 2, 3, 55, 'jaqueta-biker-preta.jpg', NULL, NULL, NULL, 21, 1, @data_migration, @data_migration),
('JAQ-MAR-G-046', 'Jaqueta Bomber Marsala', 'Jaqueta - Marsala - G - Bomber', 'Jaqueta unissex bomber com forro leve.', 'Unissex', 219.90, 32, 4, 53, 4, 56, 'jaqueta-bomber-marsala.jpg', NULL, NULL, NULL, 49, 1, @data_migration, @data_migration),
('JAQ-JEA-M-047', 'Jaqueta Trucker Jeans', 'Jaqueta - Azul Jeans - M - Trucker', 'Jaqueta jeans unissex de lavagem media.', 'Unissex', 239.90, 41, 4, 31, 3, 57, 'jaqueta-trucker-jeans.jpg', NULL, NULL, NULL, 53, 1, @data_migration, @data_migration),
('CAS-PRT-G-048', 'Casaco Puffer Grafite', 'Casaco - Grafite - G - Puffer', 'Casaco masculino acolchoado com isolamento termico.', 'Masculino', 349.90, 37, 4, 26, 4, 58, 'casaco-puffer-grafite.jpg', NULL, NULL, NULL, 25, 1, @data_migration, @data_migration),
('CAS-OLI-M-049', 'Parka Verde Oliva', 'Parka - Verde Oliva - M', 'Parka feminina resistente a garoa com cintura ajustavel.', 'Feminino', 329.90, 38, 23, 34, 3, 59, 'parka-verde-oliva.jpg', NULL, NULL, NULL, 23, 1, @data_migration, @data_migration),
('CAS-CAM-G-050', 'Trench Coat Camel', 'Sobretudo - Camel - G - Trench Coat', 'Trench coat unissex classico com cinto.', 'Unissex', 399.90, 36, 24, 21, 4, 60, 'trench-coat-camel.jpg', 'trench-coat-camel-costas.jpg', NULL, NULL, 19, 1, @data_migration, @data_migration);

SET @data_migration = NULL;
