USE Everett;

-- 50 chamados de suporte. A tabela suporte nao possui coluna de data;
-- a referencia a 2026-09-08 fica registrada no nome desta migration.
INSERT INTO suporte (idUsuario, titulo, assunto, texto, respostaAdmin, idAdminResposta) VALUES
(2, 'Duvida sobre tamanho', 'Tamanhos', 'Como escolho o tamanho correto para a camiseta?', 'Consulte a tabela de medidas disponivel na pagina do produto.', 1),
(3, 'Troca de produto', 'Trocas', 'Recebi uma calca que ficou grande e quero trocar.', 'A troca pode ser solicitada em ate sete dias apos o recebimento.', 1),
(2, 'Prazo de entrega', 'Entrega', 'Gostaria de confirmar o prazo do meu pedido.', 'O prazo atualizado pode ser consultado na area Meus Pedidos.', 1),
(3, 'Codigo de rastreio', 'Rastreamento', 'Ainda nao encontrei o codigo de rastreio.', 'O codigo sera enviado assim que a transportadora coletar o pedido.', 1),
(2, 'Pagamento recusado', 'Pagamento', 'Meu cartao foi recusado mesmo com limite disponivel.', 'Confirme os dados do cartao ou tente outra forma de pagamento.', 1),
(3, 'Estorno pendente', 'Reembolso', 'O estorno da compra cancelada ainda nao apareceu.', 'O banco pode levar ate duas faturas para processar o estorno.', 1),
(2, 'Produto com defeito', 'Qualidade', 'A costura da blusa chegou aberta.', 'Envie fotos do defeito para iniciarmos a troca sem custo.', 1),
(3, 'Cor diferente', 'Produto', 'A cor recebida parece diferente da exibida no site.', 'Pode haver variacao de tela; vamos analisar fotos do item recebido.', 1),
(2, 'Alterar endereco', 'Endereco', 'Preciso corrigir o numero do endereco de entrega.', 'A alteracao e possivel antes da emissao da nota fiscal.', 1),
(3, 'Cupom nao aplicado', 'Cupom', 'Meu cupom de primeira compra nao foi aplicado.', 'Verifique a validade e os produtos elegiveis informados no cupom.', 1),
(2, 'Nota fiscal', 'Documentos', 'Onde encontro a nota fiscal da compra?', 'A nota fiscal fica disponivel em Meus Pedidos apos a emissao.', 1),
(3, 'Pedido duplicado', 'Pedido', 'Apareceram dois pedidos iguais na minha conta.', 'Vamos conferir as cobrancas e cancelar qualquer duplicidade.', 1),
(2, 'Cancelar pedido', 'Cancelamento', 'Quero cancelar antes do envio.', 'O cancelamento foi encaminhado para verificacao do estoque.', 1),
(3, 'Produto indisponivel', 'Estoque', 'Quando o casaco voltara ao estoque?', 'Ative o aviso de disponibilidade na pagina do produto.', 1),
(2, 'Erro no cadastro', 'Conta', 'Nao consigo atualizar meu telefone.', 'Tente novamente sem espacos; se persistir, retornaremos o contato.', 1),
(3, 'Redefinir senha', 'Acesso', 'Nao recebi o email para redefinir minha senha.', 'Confira a caixa de spam e solicite um novo link em alguns minutos.', 1),
(2, 'Excluir conta', 'Privacidade', 'Gostaria de excluir meus dados e minha conta.', 'A solicitacao foi encaminhada ao responsavel por privacidade.', 1),
(3, 'Frete muito alto', 'Frete', 'O valor do frete mudou no fechamento.', 'O frete e recalculado pelo CEP e pelo volume final do carrinho.', 1),
(2, 'Entrega atrasada', 'Entrega', 'Meu pedido passou da data prevista.', 'Abrimos uma verificacao urgente com a transportadora.', 1),
(3, 'Embalagem danificada', 'Entrega', 'A caixa chegou amassada e aberta.', 'Guarde a embalagem e envie fotos para avaliacao imediata.', 1),
(2, 'Item faltando', 'Pedido', 'Faltou uma camiseta no pacote.', 'Conferiremos a separacao e providenciaremos o envio do item.', 1),
(3, 'Item incorreto', 'Pedido', 'Recebi um produto diferente do comprado.', 'Vamos gerar uma logistica reversa sem custo.', 1),
(2, 'Segunda via do boleto', 'Pagamento', 'Preciso emitir uma nova via do boleto.', 'Boletos vencidos devem ser gerados em um novo pedido.', 1),
(3, 'Pagamento via Pix', 'Pagamento', 'O Pix foi pago mas o pedido segue pendente.', 'A conciliacao pode levar alguns minutos; enviaremos a confirmacao.', 1),
(2, 'Parcelamento', 'Pagamento', 'Quais sao as opcoes de parcelamento?', 'As parcelas disponiveis aparecem antes da confirmacao da compra.', 1),
(3, 'Vale troca', 'Trocas', 'Como utilizo meu vale troca?', 'Insira o codigo do vale no campo de cupom durante o checkout.', 1),
(2, 'Troca em loja', 'Trocas', 'Posso trocar a compra online em uma loja fisica?', NULL, NULL),
(3, 'Devolucao parcial', 'Devolucao', 'Quero devolver apenas um item do pedido.', NULL, NULL),
(2, 'Medidas da peca', 'Tamanhos', 'Preciso das medidas exatas do vestido.', NULL, NULL),
(3, 'Composicao do tecido', 'Produto', 'Qual e a composicao do tecido da jaqueta?', NULL, NULL),
(2, 'Instrucao de lavagem', 'Cuidados', 'Como devo lavar o sueter sem danificar?', NULL, NULL),
(3, 'Produto sustentavel', 'Sustentabilidade', 'Este produto possui material reciclado?', NULL, NULL),
(2, 'Origem do produto', 'Produto', 'Onde esta peca foi fabricada?', NULL, NULL),
(3, 'Disponibilidade de cor', 'Estoque', 'O modelo tera reposicao na cor vinho?', NULL, NULL),
(2, 'Reserva de produto', 'Estoque', 'E possivel reservar um item do carrinho?', NULL, NULL),
(3, 'Compra para presente', 'Pedido', 'Posso enviar o pedido sem o valor da nota?', NULL, NULL),
(2, 'Embalagem para presente', 'Pedido', 'Existe opcao de embalagem para presente?', NULL, NULL),
(3, 'Mensagem no presente', 'Pedido', 'Quero incluir uma mensagem no pacote.', NULL, NULL),
(2, 'Entrega expressa', 'Frete', 'Ha entrega expressa para meu CEP?', NULL, NULL),
(3, 'Retirada no local', 'Entrega', 'Posso retirar o pedido em algum ponto?', NULL, NULL),
(2, 'Alterar forma de pagamento', 'Pagamento', 'Quero trocar a forma de pagamento do pedido.', NULL, NULL),
(3, 'Saldo do vale', 'Pagamento', 'Como consulto o saldo do meu vale compra?', NULL, NULL),
(2, 'Falha no aplicativo', 'Tecnico', 'A pagina do carrinho fecha ao adicionar um item.', NULL, NULL),
(3, 'Imagem nao carrega', 'Tecnico', 'As fotos dos produtos nao aparecem no navegador.', NULL, NULL),
(2, 'Filtro de tamanho', 'Tecnico', 'O filtro de tamanho nao retorna resultados.', NULL, NULL),
(3, 'Historico de pedidos', 'Conta', 'Um pedido antigo nao aparece no historico.', NULL, NULL),
(2, 'Email incorreto', 'Conta', 'Cadastrei meu email com uma letra errada.', NULL, NULL),
(3, 'CPF ja cadastrado', 'Conta', 'O sistema informa que meu CPF ja esta em uso.', NULL, NULL),
(2, 'Newsletter', 'Comunicacao', 'Quero parar de receber emails promocionais.', NULL, NULL),
(3, 'Atendimento acessivel', 'Acessibilidade', 'Preciso de atendimento por um canal acessivel.', NULL, NULL);
