USE Everett;

-- 50 categorias de vestuario e acessorios.
INSERT INTO categorias (nomeCategoria) VALUES
('Moda Masculina Casual'),
('Moda Feminina Casual'),
('Moda Infantil Meninos'),
('Moda Infantil Meninas'),
('Alfaiataria Masculina'),
('Alfaiataria Feminina'),
('Moda Festa'),
('Moda Fitness'),
('Moda Corrida'),
('Moda Ciclismo'),
('Moda Yoga'),
('Moda Surf'),
('Moda Praia Masculina'),
('Moda Praia Feminina'),
('Moda Gestante'),
('Moda Plus Size Masculina'),
('Moda Plus Size Feminina'),
('Moda Pet'),
('Lingerie'),
('Moda Intima Masculina'),
('Pijamas e Homewear'),
('Uniformes Profissionais'),
('Uniformes Escolares'),
('Moda Country'),
('Moda Streetwear'),
('Moda Vintage'),
('Moda Sustentavel'),
('Moda Basica'),
('Moda Premium'),
('Roupas de Inverno Masculinas'),
('Roupas de Inverno Femininas'),
('Roupas Impermeaveis'),
('Roupas Termicas'),
('Jeanswear'),
('Tricots'),
('Couro e Sinteticos'),
('Calcados Masculinos'),
('Calcados Femininos'),
('Calcados Infantis'),
('Bolsas e Mochilas'),
('Cintos'),
('Chapeus e Bones'),
('Meias'),
('Acessorios de Inverno'),
('Acessorios de Praia'),
('Moda Noiva'),
('Moda Social Masculina'),
('Moda Social Feminina'),
('Roupas para Bebes'),
('Roupas Unissex');
